
let l = ["السَّلامُ عَلَيكُم","أَهلاً","أَنا","اسمي","مِن","مدينة","في","باب","اِسم","ما؟","أهلاً بكَ","وعليكم السلام","تَشَرَّفنا","أَنتَ","أَنتِ","اِسمَك","اِسمِك","وين","من وين","نَعَم","لا","و","حجاب","بيت","شارِع","وَظيفة","أَخْبار","كتاب","حَبيبي","حَبيبتي","صَباح الْخَير","صَباح النّور","كيف","كيفك","الْحَمدُ لِلّه","تَمام","ماشي","هَيدا","هَيدي","منيحة ,منيح","مِش","تفَضَّل","تفَضَّلي","تفَضَّلوا","صاحبي","صاحِبتي","هو","هي","طالِب","طالبة","أُسْتاذ","أُستاذة","جامِعة","خُبز","دَجاج","جار","جارة","أَخ","أُخت","جديد","جَديدة","مَساء الخَير","مساء النّور","عندي","ما عندي","سُؤال","أُحِبّ","تُحِبّ","بِتحِبّي","نِمرة تليفون","أوتوبـيـس","دَرس","شاي","شـَباب","طَيِّب","عن إذنَك","عن إذنَك","صَف","مَعَ السَّلامة","اللّه يسَلّمك","صَحّ","أَبْـيَـض","أسْوَد","أَخْضر","شُكراً","عَفواً","مِن فَضلك","آسِف/ة","فيه","ما فيه","شي","شي تاني","جاهِز/ة","قَهْوة","حَليب","سُكَّر","سُكّر وَسَط","عَصير","مَيّ","يَللا","اَروح","تروحي","اِشرَب","سَيّارة","ساعة","شَجَرة","غَريب/ة","صغير/ة","كبير/ة","سَهل/ة","صَعب/ة","واسِع/ة","صَفحة","وَرَقة","اوضة","شِبّاك","كِرسي","طاولة","كَلب","بِسّة","مال","لازِم","مُمكِن","وَلا شي","وَلّا","اَشوف","تشوف","تشوفي","يشوف","تشوف","يَعني","بِناية","مَكتَب","مَكتَبة","كِلمة","جِملة","اِمتِحان","قَلَم","تَمرين","الحَمّام","قَريب/ة مِن","بِعيد/ة عَن","تَعبان/ة","بَردان/ة","مشَوِّب/ة","عَطشان/ة","جيعان /ة","زَعلان / ة","خَلْصان/ة","مَبسوط/ة","مَريض/ة","شوَيّ؛ شوَيّة","شوبَك","!سَلامتَـِك","!اللّه يِسَلّمَـِك","رِجّال","مَرَة","بِنت","وَلَد","قِصّة","قَصير/ة","طَويل/ة","حِلو/ة","لَطيف/ة","معليش!","مِشكلة","غَلَط","أَفَندِم"];
let m = [" assalaamu alaykum "," ahlan "," ana "," ismii "," min "," madiinat "," fii "," baab "," ism "," maa? "," ahlan fiik "," wa alaykumu s-salaam "," tasharrafnaa "," anta "," anti "," ismak "," ismik "," ween "," min ween "," naam "," laa "," wa "," hijab "," bayt "," sharia "," waZiifa "," akhbaar "," kitaab "," habibi "," habibti "," SabaaH al-khayr "," SabaaH an-nuur "," kiif "," kiifak "," al-Hamdu lillaah "," tamaam "," maashi "," haada "," haadi "," mniiH, mniiHa "," mish "," tfaDDal "," tfaDDli "," tfaDDlu "," SaaHbi "," SaaHibti "," huwwe "," hiyye "," Taalib "," Taalbe ","ustaadh"," ustaadha "," jaamiat "," khubz "," dejaj "," jarr "," jaara "," akh "," urth "," jadid "," jadiida "," masaa al-khayr "," masaa an-nuur "," andi "," maa andi "," suaal "," ouhib "," tuhib ","tuHibbii ","nimrit tilifuun "," autobiss "," deriss "," shay "," shabab ","Tayyib ","ayn iznak ","ayn iznik ","Saff ","maa s-salaama ","alla ysallm -ak/ -ik ","sahh ","abyat ","aswat ","akhdhar ","shukran ","afwan ","min faDlak/ik ","aasif/ aasifa ","fii ","maa fii ","shii ","shi taani ","jaahiz/jaahze ","qahwa ","Haliib ","sukkar ","sukkar wasaT ","aSiir ","mayy ","yalla ","arouh ","trouhii ","ushrab ","seyara ","seaah ","shejra ","ghariib/e ","zakhir/e ","kbiir/e ","sahl/e ","saab/e ","wasseah/wassah ","sefha ","wara a ","oudha ","shubbak ","kursii ","tauleh ","kelb ","bisseh ","maal ","laazim ","mumkin ","walaashi ","walaa ","ashouff ","teshouff ","teshouffi ","yeshouff ","tshouff ","yaanii ","binaye ","mektab ","mektabe ","kilmeh ","jimleh ","imtihab ","qalam ","tamriin ","alhamam ","qarib/e min ","bayd/a an ","tahben/a ","berden/a ","musheweb/a ","aTshaan/a ","jiaen/i ","zaelen/i ","khalsaan/a ","mebsut/a ","merid/a ","shuweya ","shubek ","salaamtak/ik ","allah yssalmak/ik ","rijel ","maraa ","binet ","walad ","qissaa ","qssiir/a ","Tawil/a ","haloo/wa ","latif/i ","maelish ","mishkleh ","ghalaT ","ah fendim "];
let k = ["Greetings","Hello","I","My name","From","The city of …","In","door","name","what?","(reply) to ahlan wa sahlan","(reply to) assalaamu alaykum","Nice to meet you!","you (masculine)","you (feminine)","your name (masculine)","your name (feminine)","where","from where","yes","no","and","veil, head covering","house","street","homework","news","book","my (male) dear, darling","my (female) dear, darling","Good morning!","(response to) Good morning!","How","How are you?","(response to) How are you?","great, fine","OK","this (masc.)","(this (fem.)","good (masc.) / good (fem.)","(am/are/is) not"," please come in, go ahead (to a male) "," please come in, go ahead (to a female) "," please come in, go ahead (plural) ","my (male) friend","my (female) friend","he/it (masc.)","she/it (fem.)","student (male)","your student (female)","professor, teacher(male)","professor, teacher(female)","university of...","bread","chicken","neighbor (male)","neighbor (female)","brother","sister","new (masc.)","new (fem.)","Good evening!","(response to) Good evening!","I have","I don't have","question","I love","you (masc.) love","you (fem.) love","telephone number","bus","lesson","tea","young people; guys (including mixed gender)","good, kind-hearted (as adjective); OK (as an interjection) ","may I be excused?  (what to say when you have to leave)(masculin)","may I be excused?  (what to say when you have to leave) (fem.) ","class; classroom","good-bye","(reply to) maa s-salaama (masc./fem.) ","right! correct!","white","black","green","thank you","you're welcome","please(masc/fem.)","sorry!(masc/fem)","there is","there isn't","something","something else","ready(masc/fem)","coffee","milk","sugar","medium sugar","juice","water","Let's go!","you (masc.) go","you (fem.) go","I drink","car, automobile","watch, clock; hour","tree","strange(masc/fem)","small; young (masc/fem)","large, old(masc/fem)","easy(masc/fem)","difficult; hard(masc/fem)","wide; spacious","page","(piece of) paper","room","window","chair","table","dog","cat","money","must, need to, have to (fixed form; with following verb)","it is possible, can (fixed form, with following verb)","nothing","or","I see (watch)","you (masc.) see","you (fem.) see ","he sees ","she sees ","(that) means, that is ","building ","office, desk ","library; bookstore ","word ","sentence ","test, examination ","pen or pencil ","drill, exercise ","bathroom ","close to, near ","far from (masc./fem.)","tired","cold","hot","thirsty","hungry","angry","exhausted","happy","sick","a little","What's wrong (with you?)","Feel better! Get well soon!","(response to) salamtak","man","woman","girl","boy","story","short (masc./fem.)","tall, long (masc./fem.)","beautiful (masc./fem.)","nice, pleasant (masc./fem.)","never mind! Don't worry about it! sorry!","problem","wrong, a mistake","sir/madam"];
const body = document.body;
for(let i = 0; i < l.length; i++){//for i in range(len)
    
    //console.log(l[i]);
    //document.getElementById("Words").innerHTML = k[i];
    //document.getElementById("transWords").innerHTML = m[i];
   // document.getElementById("araWords").innerHTML = l[i];

    const labelElement = document.createElement("h2");
    const labelElement1 = document.createElement("label");
    const labelElement2 = document.createElement("label");

    // Set the text content of the label to the current item in the list
    labelElement.textContent = l[i];
    labelElement1.textContent = m[i];
    labelElement2.textContent = k[i];

    // Append the label element to the body
    body.appendChild(labelElement);
    body.appendChild(labelElement1);
    body.appendChild(labelElement2);

    // Add a line break between labels for better spacing
    body.appendChild(document.createElement("br"));
    
}